### ISSUE TITLE
[0.9.1 Server] NPE when removing Relocators

### ISSUE THREAD

**Issue by luxifr** [xJon/The-1.7.10-Pack#1192]
Title says it... Crash report is attached. It's pretty reproducible.

```
[13:15:14] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NullPointerException
        at TRelocator$$PassThrough$class.getTileEntity(Unknown Source) ~[?:?]
        at TileMultipart_cmp$$0.getTileEntity(Unknown Source) ~[?:?]
        at com.dynious.refinedrelocation.grid.relocator.RelocatorGridLogic.tryOutputAndReturnConnections(RelocatorGridLogic.java:77) ~[RelocatorGridLogic.class:?]
        at com.dynious.refinedrelocation.grid.relocator.RelocatorGridLogic.findOutput(RelocatorGridLogic.java:39) ~[RelocatorGridLogic.class:?]
        at com.dynious.refinedrelocation.tileentity.TileRelocator.insert(TileRelocator.java:726) ~[TileRelocator.class:?]
        at com.dynious.refinedrelocation.compat.part.PartRelocator.insert(PartRelocator.java:278) ~[PartRelocator.class:?]
        at TRelocator$$PassThrough$class.insert(Unknown Source) ~[?:?]
        at TileMultipart_cmp$$0.insert(Unknown Source) ~[?:?]
        at com.dynious.refinedrelocation.grid.relocator.RelocatorModuleCrafting.outputStack(RelocatorModuleCrafting.java:240) ~[RelocatorModuleCrafting.class:?]
        at com.dynious.refinedrelocation.grid.relocator.RelocatorModuleCrafting.onUpdate(RelocatorModuleCrafting.java:169) ~[RelocatorModuleCrafting.class:?]
        at com.dynious.refinedrelocation.tileentity.TileRelocator.func_145845_h(TileRelocator.java:107) ~[TileRelocator.class:?]
        at com.dynious.refinedrelocation.compat.part.PartRelocator.update(PartRelocator.java:114) ~[PartRelocator.class:?]
        at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:82) ~[TileMultipart$$anonfun$updateEntity$1.class:?]
        at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:82) ~[TileMultipart$$anonfun$updateEntity$1.class:?]
        at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:76) ~[TileMultipart.class:?]
        at codechicken.multipart.TileMultipart.func_145845_h(TileMultipart.scala:82) ~[TileMultipart.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
        ... 4 more
```
[crash-2016-07-17_13.15.14-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/367798/crash-2016-07-17_13.15.14-server.txt)

**Comment by luxifr** [comment]
I thought maybe there's an issue with the crafting module in my network so I removed it.. still no dice - now it just happens somewhere else... 2nd crash report attached as well
[crash-2016-07-17_13.21.37-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/367799/crash-2016-07-17_13.21.37-server.txt)

**Comment by xJon** [comment]
Any chance you can report the issue [there](https://github.com/Dynious/RefinedRelocation/issues), so we can get more information?
In any case, The 1.7.10 Pack uses the latest version of Refined Relocation.

**Comment by luxifr** [comment]
@xJon thanks for pointing me there :) it seems there's already an issue opened: https://github.com/Dynious/RefinedRelocation/issues/387

I've attached my crashlogs there as well
