### ISSUE TITLE
Mods not showing up in the server.

### ISSUE THREAD

**Issue by camelCaseText** [xJon/The-1.7.10-Pack#1229]
I was trying to set up a small server for my friends and I last night and all was going fine. After playing for awhile though, we began to realize that the world generation and everything in it was still vanilla. The only  things affected were our UIs (minimap, new menus, etc.). I tried to spawn in some items from mods using NEI, but I kept getting "there is no such item with ID ####". I'm pretty besides myself right now about what more I can do to resolve the problem.

**Comment by mandm635** [comment]
Server output?

**Comment by camelCaseText** [comment]
[18:05:13 INFO]: Starting minecraft server version 1.7.10
[18:05:13 ERROR]: Exception handling console input
java.io.IOException: The handle is invalid
	at java.io.FileInputStream.readBytes(Native Method) ~[?:1.8.0_91]
	at java.io.FileInputStream.read(Unknown Source) ~[?:1.8.0_91]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[?:1.8.0_91]
	at java.io.BufferedInputStream.read(Unknown Source) ~[?:1.8.0_91]
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source) ~[?:1.8.0_91]
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[?:1.8.0_91]
	at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[?:1.8.0_91]
	at java.io.InputStreamReader.read(Unknown Source) ~[?:1.8.0_91]
	at java.io.BufferedReader.fill(Unknown Source) ~[?:1.8.0_91]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_91]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_91]
	at lv.run(SourceFile:79) [minecraft_server.1.7.10.jar:?]
[18:05:13 INFO]: Loading properties
[18:05:13 INFO]: Default game type: SURVIVAL
[18:05:13 INFO]: Generating keypair
[18:05:13 INFO]: Starting Minecraft server on *:25565
[18:05:13 INFO]: Preparing level "world"
[18:05:13 INFO]: Preparing start region for level 0
[18:05:14 INFO]: Done (0.543s)! For help, type "help" or "?"

**Comment by xJon** [comment]
You need to activate the server using the `LaunchServer.bat` file.

**Comment by camelCaseText** [comment]
Okay, so I have run the LaunchServer.bat file, changed the eula.txt file, and launched the server.exe. I'm still receiving the same messages as before regarding item IDs. I made a new world and it generated with mod items (rubber trees, other ores, etc.), the problem is that we can't interact with them. If we break a rubber tree log, nothing drops, and if we right click them they just vanish. Its weird though because if I right click a block and it vanishes, my friends still see the block and I can walk right through it. Any other ideas? Thanks!
