### ISSUE TITLE
NetworkDispatcher exception

### ISSUE THREAD

**Issue by jancoz** [xJon/The-1.7.10-Pack#1337]
When connecting to the server I get an error, and can't connect. I
The server log:
```
[20:10:50] [Netty IO #4/INFO] [FML]: Client protocol version 2
[20:10:50] [Netty IO #4/INFO] [FML]: Client attempting to join with 233 mods : Growthcraft|Rice@1.7.10-2.7.0,BuildCraft|Silicon@7.1.18,AromaBackup@0.0.0.6,DynamicLights_onFire@1.0.4,ProjRed|Expansion@4.7.0pre12.95,ExtraBees@2.0-pre14,DynamicLights@1.3.5,DynamicLights_floodLights@1.0.1,HardcoreEnderExpansion@1.8.6,MineFactoryReloaded|CompatTwilightForest@1.7.10R2.8.1,Botany@2.0-pre14,endercore@1.7.10-0.2.0.39_beta,Mystcraft@0.12.3.03,bspkrsCore@6.16,MineFactoryReloaded|CompatProjRed@1.7.10R2.8.1,BuildCraft|Robotics@7.1.18,PneumaticCraft@1.12.7-150,xreliquary@1.2,BiomesOPlenty@2.1.0,MineFactoryReloaded|CompatRailcraft@1.7.10R2.8.1,MineFactoryReloaded|CompatForestry@1.7.10R2.8.1,ForgeMultipart@1.2.0.345,magicalcropsarmour@4.0.0_PUBLIC_BETA_4,RedstoneArsenal@1.7.10R1.1.2,CoFHCore@1.7.10R3.1.3,powersuits@0.11.0.301,MineFactoryReloaded|CompatMagicalCrops@1.2.1,OpenPeripheral@0.5.1,ExtraTrees@2.0-pre14,DynamicLights_otherPlayers@1.0.7,reccomplex@0.9.7.1.1,gendustry@1.6.3.132,BuildCraft|Energy@7.1.18,IC2@2.2.827-experimental,jexclusives@1.0.1,DynamicLights_creepers@1.0.4,FML@7.10.99.99,Natura@2.2.0,NEIAddons|Forestry@1.12.14.40,magicalcrops@4.0.0_PUBLIC_BETA_4b,ThE-core@1.0.0.1,BiblioWoodsNatura@1.5,cfm@3.4.8,recipemod@0.2,factorization@1.7.10-0.8.88.7,<CoFH ASM>@000,ThermalDynamics@1.7.10R1.2.0,ProjRed|Illumination@4.7.0pre12.95,Growthcraft@1.7.10-2.7.0,TMechworks@0.2.15.106,fastleafdecay@1.4,LogisticsPipes@0.9.3.128,MekanismGenerators@9.1.1,NotEnoughItems@1.0.5.120,Thaumcraft@4.2.3.5,Waila@1.5.10,PlayerAPI@1.4,simplyjetpacks@1.5.3,appliedenergistics2-core@rv3-beta-6,NEIAddons@1.12.14.40,OpenEye@0.6,factorization.notify@1.0,BiblioCraft@1.11.5,BuildCraft|Core@7.1.18,OpenModsCore@0.9.1,Growthcraft|Hops@1.7.10-2.7.0,qCraft@1.2,bdlib@1.9.4.109,NEIAddons|Developer@1.12.14.40,Morph@0.9.2,CartFixes@0.1.0,ProjRed|Transmission@4.7.0pre12.95,Sync@4.0.0,WR-CBE|Logic@1.4.1.11,MineFactoryReloaded|CompatAppliedEnergistics@1.7.10R2.8.1,inventorytweaks@1.59-dev-156-af3bc68,MineFactoryReloaded|CompatBuildCraft@1.7.10R2.8.1,defaultworldgenerator@0.1-b13,Growthcraft|Cellar@1.7.10-2.7.0,OpenBlocks@1.5.1,EnderStorage@1.4.7.38,ForbiddenMagic@1.7.10-0.575,EnderTech@1.7.10-0.3.2.405,warpbook@2.0.null,testdummy@1.0,crashlogadditions@1.1,MineFactoryReloaded|CompatForgeMicroblock@1.7.10R2.8.1,CarpentersBlocks@3.3.8.1,eplus@4.0.0..73,Growthcraft|Bamboo@1.7.10-2.7.0,StevesWorkshop@0.5.1,EnderIO@1.7.10-2.3.0.429_beta,Translocator@1.1.2.16,funkylocomotion@1.0,neiintegration@1.1.2,MrTJPCoreMod@1.1.0.33,Roguelike@1.5.0,NEIAddons|Botany@1.12.14.40,numina@0.4.0.131,thaumicenergistics@1.0.0.5,Aroma1997Core@1.0.2.16,CodeChickenCore@1.0.7.47,BigReactors@0.4.3A,Mekanism@9.1.1,compacter@1.1.0.12,MekanismTools@9.1.1,BinniePatcher@1.8.2,ThaumicTinkerer-preloader@0.1,aobd@2.9.2,MineMenu@1.2.0,necromancy@1.7.2,Doge@0.5.2,Baubles@1.0.1.10,ProjRed|Core@4.7.0pre12.95,denseores@1.0,ProjRed|Exploration@4.7.0pre12.95,Forestry@4.2.16.64,squidless@0.6.1,OpenMods@0.9.1,BiblioWoodsBoP@1.9,GalacticraftCore@3.0.12,DynamicLights_thePlayer@1.1.3,ChocoPatcher@1.1,ObsidiPlates@3.0.0.18,Grinder@4.0.0,flansmod@4.10.0,DeathCounter@4.0.0,HardcoreQuesting@4.4.4,ForgeMicroblock@1.2.0.345,iChunUtil@4.2.2,PortalGun@4.0.0-beta-6,ThaumicExploration@0.6.0,EnderZoo@1.7.10-1.0.15.32,MagicBees@2.4.3,ProjRed|Integration@4.7.0pre12.95,factorization.misc@1.7.10-0.8.88.7,bookshelf@1.0.4.172,RenderPlayerAPI@1.4,OpenComputers@1.6.0.9,McMultipart@1.2.0.345,ProjRed|Fabrication@4.7.0pre12.95,ExtraUtilities@1.2.12,Micdoodlecore@,Railcraft@9.12.2.0,WR-CBE|Addons@1.4.1.11,IC2NuclearControl@2.4.2a,ThermalFoundation@1.7.10R1.2.5,MineFactoryReloaded|CompatVanilla@1.7.10R2.8.1,StevesCarts@2.0.0.b18,MCFrames@1.0,DynamicLights_dropItems@1.0.7,DynamicLights_entityClasses@1.0.1,neresources@0.1.0.ManuallyBuilt,FastCraft@1.23,Forge@10.13.4.1614,Aroma1997sDimension@1.0,HatStand@4.0.0,OpenComputers|Core@1.6.0.9,ThaumicTinkerer@unspecified,PiP@4.0.0,RefinedRelocation@1.1.28,JABBA@1.2.2,MineFactoryReloaded|CompatIC2@1.7.10R2.8.1,ProjRed|Transportation@4.7.0pre12.95,DefenseTech@1.0.1,TiCTooltips@1.2.5,NEIAddons|CraftingTables@1.12.14.40,NEIAddons|ExNihilo@1.12.14.40,WailaHarvestability@1.1.6,libsandstone@1.0.0,Botania@r1.8-248,Hats@4.0.1,AdvancedMachines@1.1.6,ProjRed|Compatibility@4.7.0pre12.95,ForgeRelocation@0.0.1.4,extracells@2.3.14,TConstruct@1.7.10-1.8.8.build988,asielib@0.4.6,StevesFactoryManager@A93,BinnieCore@2.0-pre14,inpure|core@1.7.10R1.0.0B9,ivtoolkit@1.2.1,RelocationFMP@0.0.1.2,Genetics@2.0-pre14,mcp@9.05,Mantle@1.7.10-0.3.2.jenkins191,appliedenergistics2@rv3-beta-6,thaumcraftneiplugin@@VERSION@,AromaBackupRecovery@1.0,OpenPeripheralIntegration@0.5,MineFactoryReloaded|CompatTConstruct@1.7.10R2.8.1,Growthcraft|Bees@1.7.10-2.7.0,WR-CBE|Core@1.4.1.11,harvestcraft@1.7.10j,ThermalExpansion@1.7.10R4.1.4,CompactSolars@4.4.39.315,TwilightForest@2.3.8dev,BuildCraft|Factory@7.1.18,MineFactoryReloaded|CompatThaumcraft@1.7.10R2.8.1,computronics@1.6.1,GraviSuite@1.7.10-2.0.3,OpenPeripheralCore@1.3,NEIAddons|AppEng@1.12.14.40,progressiveautomation@1.6.35,Growthcraft|Grapes@1.7.10-2.7.0,Growthcraft|Apples@1.7.10-2.7.0,magicalcropsdeco@4.0.0_PUBLIC_BETA_4a,MineFactoryReloaded@1.7.10R2.8.1,GalacticraftMars@3.0.12,BuildCraft|Compat@7.1.5,wailaplugins@MC1.7.10-0.2.0-null,ComputerCraft@1.75,HelpFixer@1.0.7,itlt@0.0.8,Growthcraft|Milk@1.7.10-2.7.0,AWWayofTime@v1.3.3,IronChest@6.0.62.742,MineFactoryReloaded|CompatThermalExpansion@1.7.10R2.8.1,DynamicLights_mobEquipment@1.0.5,ChickenChunks@1.3.4.19,DynamicLights_flameArrows@1.0.0,Treecapitator@1.7.10,NetherOres@1.7.10R2.3.1,debug@1.0,statues@2.1.4,BuildCraft|Transport@7.1.18,Aroma1997CoreHelper@1.0.2.16,chisel@2.9.5.11,StevesAddons@0.10.16,Backpack@2.0.1,Growthcraft|Fishtrap@1.7.10-2.7.0,witchery@0.24.1,BuildCraft|Builders@7.1.18
[20:10:50] [Netty IO #4/INFO] [FML]: Attempting connection with missing mods [colorchat, Morpheus] at CLIENT
[20:10:50] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[20:10:50] [Server thread/INFO]: jancoz[] logged in with entity id 2999 at (-748.5934044470836, 70.36660004615786, 94.91863159397055)
[20:10:51] [Server thread/INFO]: jancoz joined the game
[20:10:51] [Server thread/INFO] [EnderCore]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
[20:10:51] [Server thread/INFO] [MineMenu]: SERVER: MineMenu is installed. Sending server response packet
[20:10:51] [Server thread/INFO] [EnderCore]: Sending server configs to client for tterrag.wailaplugins.config.WPConfigHandler
[20:10:51] [Server thread/INFO] [Waila]: Player EntityPlayerMP['jancoz'/2999, l='world', x=-748.59, y=70.37, z=94.92] connected. Sending ping
[20:10:51] [Server thread/INFO] [Mekanism]: Sent config to 'jancoz.'
[20:11:14] [Netty IO #4/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_121]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_121]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_121]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_121]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_121]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[20:11:14] [Server thread/INFO]: jancoz lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Connection reset by peer], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[20:11:14] [Server thread/INFO]: jancoz left the game
```

It seems to be server side since I can't login from all my machines to the server.
I tried removing my userfiles from the NEI folder. 
I tried restoring an hour old backup of "world" (which was when I was still logged in a playing). 

After I friend finding out the problem I asked a friend of mine to login, and he managed to, for about 10 seconds. He crashed right after he walked through a teleporter (Mekanism). I asked him to do it again but this time walk in the teleporter right after you login, and he crashed right after walking in it. 

I figured it might be the location (which is my house, got all kinds of tools there, reactors, etc etc..). I changed the cordinates of my user file and I managed to login again. The moment I went back to my house the game crashed again. 

Any idea what the problem is and how I can solve it?

**Comment by jancoz** [comment]
Crash log (apologies for not providing it earlier): http://pastebin.com/Ljjy27sz

**Comment by Curunir** [comment]
That crash log has a completely different error description than the fragment you posted above. Are you sure that is the same issue? Check timestamps.

**Comment by jancoz** [comment]
I'm 100% sure it's the right crashlog. The cordinates noted in the log match the chunk(s) where the crash keeps occuring.

**Comment by Curunir** [comment]
I only ever got that error when running OptiFine, although the log doesn't indicate you have that. If this happens at specific world coordinates, backup the world and try to remove the source of the problem with an editor.

**Comment by Curunir** [comment]
Issue owner seems to have lost interest in this.
