### ISSUE TITLE
Server connection problem

### ISSUE THREAD

**Issue by maxrightgame** [xJon/The-1.7.10-Pack#1354]
Hi,
experienced error while connecting to local server

http://paste.ubuntu.com/24182938/ fml log
http://paste.ubuntu.com/24182946/ server log

**Comment by xJon** [comment]
```
[18:29:26] [Server thread/ERROR] [FML/]: There was a critical exception handling a packet on channel FML
java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217) ~[add.class:?]
	at hardcorequesting.quests.QuestTaskMob$Mob.save(QuestTaskMob.java:138) ~[QuestTaskMob$Mob.class:?]
	at hardcorequesting.quests.QuestTaskMob.save(QuestTaskMob.java:308) ~[QuestTaskMob.class:?]
	at hardcorequesting.quests.Quest.saveAll(Quest.java:1876) ~[Quest.class:?]
	at hardcorequesting.quests.QuestLine.sendServerSync(QuestLine.java:90) ~[QuestLine.class:?]
	at hardcorequesting.PlayerTracker.onPlayerLogin(PlayerTracker.java:35) ~[PlayerTracker.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_950_PlayerTracker_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:550) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:180) ~[oi.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) ~[NetworkDispatcher.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:463) ~[NetworkDispatcher.class:?]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17) ~[HandshakeCompletionHandler.class:?]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) ~[HandshakeCompletionHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) ~[FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```
Seems like the server has some corrupted HQM data for your player. Try to reset it in the save.

**Comment by maxrightgame** [comment]
But i have no files of HQM in world folder

**Comment by xJon** [comment]
What about `HardcoreQuesting`?

**Comment by maxrightgame** [comment]
Same as above

**Comment by xJon** [comment]
You should have a `HardcoreQuesting` inside of your world save folder.
