### ISSUE TITLE
Fatal Error Game Crash

### ISSUE THREAD

**Issue by Kane176** [xJon/The-1.7.10-Pack#1409]
From Log file, Game Crash, newest Version, Fresh install, Singleplayer, Gamemode 1, Site 3

[18:54:14] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering item
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1092) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_94608_d(ItemStack.java:123) ~[add.class:?]
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:161) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563) ~[bny.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:929) ~[bfl.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:760) ~[bfl.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78) ~[bex.class:?]
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38) ~[bfo.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638) ~[bfl.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) ~[blt.class:?]
	... 9 more

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Kane176** [comment]
Have Only the Complete Log, Sry i Downgrade and the other logs are gone
http://paste.ubuntu.com/25055744/

**Comment by Kane176** [comment]
sry ive found it
http://paste.ubuntu.com/25056851/

**Comment by Curunir** [comment]
So you are basically asking why flipping through Creative tabs crashes your game. This is a known issue can cannot be fixed (because Mojang would have to fix it). Your workaround is using NEI also in Creative.
