### ISSUE TITLE
A fatal error has occured connection terminated

### ISSUE THREAD

**Issue by xPiwkoPL** [xJon/The-1.7.10-Pack#1412]
http://paste.ubuntu.com/25061114/
https://www.youtube.com/watch?v=6qL2Y2Sd5UQ&feature=youtu.be

**Comment by xJon** [comment]
Did you try to reinstall the modpack?

**Comment by xPiwkoPL** [comment]
like 3-4 times

**Comment by xPiwkoPL** [comment]
tried also previous versions

**Comment by xPiwkoPL** [comment]
got 8gb of ram 3gb for minecraft

**Comment by xPiwkoPL** [comment]
i used 4gb for minecraft also, still doesnt work

**Comment by xJon** [comment]
Whoops, my bad. I've missed the error in the log, but I've found it now:
> [15:02:30] [Client thread/ERROR] [FML/]: There was a critical exception handling a packet on channel Morph
java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonObject
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService$GameProfileSerializer.deserialize(YggdrasilAuthenticationService.java:116) ~[YggdrasilAuthenticationService$GameProfileSerializer.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService$GameProfileSerializer.deserialize(YggdrasilAuthenticationService.java:1) ~[YggdrasilAuthenticationService$GameProfileSerializer.class:?]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:868) ~[Gson.class:?]
	at com.google.gson.Gson$1.deserialize(Gson.java:126) ~[Gson$1.class:?]
	at com.mojang.authlib.yggdrasil.response.ProfileSearchResultsResponse$Serializer.deserialize(ProfileSearchResultsResponse.java:44) ~[ProfileSearchResultsResponse$Serializer.class:?]
	at com.mojang.authlib.yggdrasil.response.ProfileSearchResultsResponse$Serializer.deserialize(ProfileSearchResultsResponse.java:1) ~[ProfileSearchResultsResponse$Serializer.class:?]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:689) ~[Gson.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:75) ~[YggdrasilAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:53) ~[YggdrasilGameProfileRepository.class:?]
	at ichun.common.core.EntityHelperBase.getPartialGameProfileFromName(EntityHelperBase.java:151) ~[EntityHelperBase.class:?]
	at ichun.common.core.EntityHelperBase.getFullGameProfileFromName(EntityHelperBase.java:101) ~[EntityHelperBase.class:?]
	at morph.common.morph.MorphState.createPlayer(MorphState.java:168) ~[MorphState.class:?]
	at morph.common.morph.MorphState.readTag(MorphState.java:118) ~[MorphState.class:?]
	at morph.common.packet.PacketMorphStates.handleClient(PacketMorphStates.java:83) ~[PacketMorphStates.class:?]
	at morph.common.packet.PacketMorphStates.execute(PacketMorphStates.java:62) ~[PacketMorphStates.class:?]
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:84) ~[ChannelHandler$PacketExecuter.class:?]
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:66) ~[ChannelHandler$PacketExecuter.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

It seems that the Morph mod is giving you trouble, but that's weird and shouldn't happen.
As a first fix, try to remove it and launch the game. If that works, try to re-add it and see what happens.

**Comment by xPiwkoPL** [comment]
i tried to remove morph earlie bcs i read another issue, but its automatically redownloaded while launching a modpack

**Comment by xPiwkoPL** [comment]
ok now it worked removing morph

**Comment by xPiwkoPL** [comment]
i5-7500
gtx 1070
8gb ram
laggings sometimes

**Comment by xJon** [comment]
Try to disable VSync and change the FPS limitation to unlimited.
