### ISSUE TITLE
Connection Lost: Internal Server Error. When Breaking blocks on Server

### ISSUE THREAD

**Issue by carloslockward** [xJon/The-1.7.10-Pack#1472]
Im not using Optifine.

The error occurs randomly when breaking any kind of block. All players on the server get kicked out.

Full Log: https://paste.ubuntu.com/26296023/

Error Part of the log:

[17:33:01] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$BreakEvent@327194aa:
java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_152]
	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_152]
	at java.lang.String.format(Unknown Source) ~[?:1.8.0_152]
	at factorization.shared.Core.logInfo(Core.java:319) ~[Core.class:?]
	at factorization.docs.DistributeDocs.breakBlock(DistributeDocs.java:78) ~[DistributeDocs.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_481_DistributeDocs_breakBlock_BreakEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:467) ~[ForgeHooks.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:259) ~[mx.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:217) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:498) ~[nh.class:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53) ~[ji.class:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) ~[ji.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[17:33:01] [Server thread/ERROR] [FML/]: Index: 4 Listeners:
[17:33:01] [Server thread/ERROR] [FML/]: 0: NORMAL
[17:33:01] [Server thread/ERROR] [FML/]: 1: ASM: team.chisel.item.chisel.ChiselController@20855a3c onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:33:01] [Server thread/ERROR] [FML/]: 2: ASM: crazypants.enderio.machine.spawner.BlockPoweredSpawner@1d020382 onBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:33:01] [Server thread/ERROR] [FML/]: 3: ASM: factorization.utiligoo.ItemGoo@6e8f1b47 mineGooeyBlocks(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:33:01] [Server thread/ERROR] [FML/]: 4: ASM: factorization.docs.DistributeDocs@38da7ae breakBlock(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:33:01] [Server thread/ERROR] [FML/]: 5: ASM: portalgun.common.core.EventHandler@5765e498 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:33:01] [Server thread/ERROR] [FML/]: 6: ASM: bspkrs.treecapitator.forge.ForgeEventHandler@2273c52b onBlockHarvested(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:33:01] [Server thread/ERROR] [FML/]: 7: ASM: twilightforest.TFEventListener@1ed4212e breakBlock(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:33:01] [Server thread/ERROR] [FML/]: 8: ASM: com.carpentersblocks.util.handler.EventHandler@59031173 onBlockBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:33:01] [Server thread/ERROR] [FML/]: 9: ASM: com.enderio.core.common.handlers.XPBoostHandler@535ff707 handleBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:33:01] [Server thread/ERROR] [FML/]: 10: ASM: li.cil.oc.common.EventHandler$@2bf4b970 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:33:01] [Server thread/ERROR] [FML/]: 11: ASM: extracells.util.ExtraCellsEventHandler@2634d606 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:33:01] [Server thread/ERROR] [FML/]: 12: ASM: thaumic.tinkerer.common.enchantment.ModEnchantmentHandler@7de0388b onBreakBlock(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:33:01] [Server thread/ERROR] [FML/]: 13: ASM: stevesaddons.naming.EventHandler@78347cd blockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:33:01] [Server thread/ERROR] [FML/]: 14: ASM: buildcraft.robotics.map.MapManager@9b82499 blockBroken(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[17:33:01] [Server thread/DEBUG] [NotEnoughItems/]: Unloading Player: LockwardCraft
[17:33:36] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
[17:34:21] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
[17:35:06] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
[17:35:51] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world

**Comment by xJon** [comment]
Weird. Factorization seems to be acting strange.
Try changing the build to this version: https://asie.pl/files/mods/Factorization/Factorization-1.7.10-0.8.109.jar
and update me.

**Comment by xJon** [comment]
Closed due to inactivity.
Should also be fixed in v0.9.8 and above.
Will reopen if requested.
