### ISSUE TITLE
Server will not start

### ISSUE THREAD

**Issue by Nebnitan** [xJon/The-1.7.10-Pack#1568]
ok so the minecraft server is being hosted by NFOServers.com. it doesnt give me any crash reports. here are all the logs i copied from the console. any info you need is yours all you need to do is tell me where to find it. its 6 am and ive been banging my head on the wall for the past 9 hours.  any and all help appreciated

[06:23:21] [Server thread/INFO] [STDOUT]: [com.flansmod.common.FlansMod:log:549]: [Flan's Mod] Loaded mechaItem.
[06:23:21] [Server thread/INFO] [STDOUT]: [com.flansmod.common.FlansMod:log:549]: [Flan's Mod] Loaded mecha.
[06:23:21] [Server thread/INFO] [STDOUT]: [com.flansmod.common.FlansMod:log:549]: [Flan's Mod] Loaded tool.
[06:23:21] [Server thread/INFO] [STDOUT]: [com.flansmod.common.FlansMod:log:549]: [Flan's Mod] Loaded armour.
[06:23:47] [Server thread/INFO] [STDOUT]: [com.flansmod.common.FlansMod:log:549]: [Flan's Mod] Loaded armourBox.
[06:25:07] [Server thread/INFO] [STDOUT]: [com.flansmod.common.FlansMod:log:549]: [Flan's Mod] Loaded box.
[06:25:16] [Server thread/INFO] [STDOUT]: [com.flansmod.common.FlansMod:log:549]: [Flan's Mod] Tried to add m4Carbine to player class gignAssault1 but the item did not exist
[06:25:20] [Server thread/INFO] [STDOUT]: [com.flansmod.common.FlansMod:log:549]: [Flan's Mod] Tried to add mp5k to player class gignDualWield1 but the item did not exist
[06:25:24] [Server thread/INFO] [STDOUT]: [com.flansmod.common.FlansMod:log:549]: [Flan's Mod] Tried to add mp5k+flanMWSilencer to player class gignSniper2 but the item did not exist
[06:26:39] [Server thread/INFO] [STDOUT]: [com.flansmod.common.FlansMod:log:549]: [Flan's Mod] Loaded playerClass.
[06:26:39] [Server thread/INFO] [STDOUT]: [com.flansmod.common.FlansMod:log:549]: [Flan's Mod] Loaded team.
[06:26:39] [Server thread/INFO] [STDOUT]: [com.flansmod.common.FlansMod:log:549]: [Flan's Mod] Preinitializing complete.
[06:26:49] [Server thread/INFO] [OpenComputers]: Successfully injected component logic into class thaumic.tinkerer.common.block.tile.TileAspectAnalyzer.
[06:26:49] [Server thread/INFO] [OpenComputers]: Successfully injected component logic into class thaumic.tinkerer.common.block.tile.TileGolemConnector.
[06:26:52] [Server thread/INFO] [OpenComputers]: Successfully injected component logic into class thaumic.tinkerer.common.block.tile.TileMagnet.
[06:26:53] [Server thread/INFO] [OpenComputers]: Successfully injected component logic into class thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.
[06:27:32] [Server thread/INFO] [MagicBees]: Preinit started
[06:27:32] [CoFHUpdater:RedstoneArsenal/ERROR] [RedstoneArsenal]: Update check for Redstone Arsenal failed.
java.io.FileNotFoundException: https://raw.githubusercontent.com/CoFH/VERSION/master/RedstoneArsenal
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890) ~[?:1.8.0_152]
at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91) ~[?:1.8.0_152]
at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484) ~[?:1.8.0_152]
at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482) ~[?:1.8.0_152]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782) ~[?:1.8.0_152]
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481) ~[?:1.8.0_152]
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_152]
at java.net.URL.openStream(URL.java:1045) ~[?:1.8.0_152]
at cofh.mod.updater.UpdateCheckThread.run(UpdateCheckThread.java:55) [UpdateCheckThread.class:?]
[06:27:57] [Server thread/INFO] [MagicBees]: Found nugget of type IRON
[06:27:57] [Server thread/INFO] [MagicBees]: Found nugget of type COPPER
[06:27:57] [Server thread/INFO] [MagicBees]: Found nugget of type TIN
[06:27:57] [Server thread/INFO] [MagicBees]: Found nugget of type SILVER
[06:27:57] [Server thread/INFO] [MagicBees]: Found nugget of type LEAD
[06:27:57] [Server thread/INFO] [MagicBees]: Found nugget of type DIAMOND
[06:27:57] [Server thread/INFO] [MagicBees]: Disabled nugget DIAMOND
[06:27:57] [Server thread/INFO] [MagicBees]: Found nugget of type EMERALD
[06:27:57] [Server thread/INFO] [MagicBees]: Found nugget of type APATITE
[06:27:57] [Server thread/INFO] [MagicBees]: Disabled nugget APATITE
[06:27:57] [Server thread/INFO] [MagicBees]: Preinit completed
[06:27:57] [Server thread/INFO] [gendustry]: IC2 Version: IC2 2.2.827-experimental
[06:27:57] [Server thread/INFO] [gendustry]: RF API Version: CoFHAPI 1.7.10R1.0.10
[06:27:57] [Server thread/INFO] [gendustry]: Available Forestry species roots:
[06:27:57] [Server thread/INFO] [gendustry]: * rootBees - forestry.apiculture.genetics.BeeHelper
[06:27:57] [Server thread/INFO] [gendustry]: * rootTrees - forestry.arboriculture.genetics.TreeHelper
[06:27:57] [Server thread/INFO] [gendustry]: * rootButterflies - forestry.lepidopterology.genetics.ButterflyHelper
[06:27:57] [Server thread/INFO] [gendustry]: * rootFlowers - binnie.botany.genetics.FlowerHelper
[06:27:57] [Server thread/INFO] [bdlib]: Loading internal config files for mod Gendustry
[06:27:57] [Server thread/INFO] [bdlib]: Loading config: jar:file:/servers/ruby/minecraft/mods/gendustry-1.6.3.132-mc1.7.10.jar!/assets/gendustry/config/tuning.cfg
[06:27:57] [Server thread/INFO] [bdlib]: Loading config: jar:file:/servers/ruby/minecraft/mods/gendustry-1.6.3.132-mc1.7.10.jar!/assets/gendustry/config/recipes.cfg
[06:28:16] [Server thread/INFO] [bdlib]: Loading config: jar:file:/servers/ruby/minecraft/mods/gendustry-1.6.3.132-mc1.7.10.jar!/assets/gendustry/config/bees_color.cfg
[06:28:16] [Server thread/INFO] [bdlib]: Loading config: jar:file:/servers/ruby/minecraft/mods/gendustry-1.6.3.132-mc1.7.10.jar!/assets/gendustry/config/bees_patreon.cfg
[06:28:16] [Server thread/INFO] [bdlib]: Loading user config files for mod Gendustry
[06:28:16] [Server thread/INFO] [bdlib]: Config loading for mod Gendustry finished
[06:28:16] [Server thread/INFO] [gendustry]: Created 52 BC triggers for Forestry error codes
[06:28:16] [Server thread/INFO] [bdlib]: Loaded creative tabs for gendustry
[06:28:33] [Server thread/INFO] [gendustry]: Items loaded
[06:28:33] [Server thread/INFO] [gendustry]: Fluids loaded
[06:28:33] [Server thread/INFO] [gendustry]: Blocks loaded
[06:28:52] [Server thread/INFO] [gendustry]: Machines loaded
[06:28:53] [Server thread/WARN] [Growthcraft]: Growthcraft Config file growthcraft/core.conf has changed, be sure for check for updates.
[06:28:53] [Server thread/WARN] [Growthcraft|Cellar]: Growthcraft|Cellar Config file growthcraft/cellar.conf has changed, be sure for check for updates.
[06:29:14] [Server thread/WARN] [Growthcraft|Apples]: Growthcraft|Apples Config file growthcraft/apples.conf has changed, be sure for check for updates.
[06:29:14] [Server thread/WARN] [Growthcraft|Bamboo]: Growthcraft|Bamboo Config file growthcraft/bamboo.conf has changed, be sure for check for updates.
[06:29:14] [Server thread/WARN] [Growthcraft|Bees]: Growthcraft|Bees Config file growthcraft/bees.conf has changed, be sure for check for updates.
[06:29:15] [Server thread/WARN] [Growthcraft|Fishtrap]: Growthcraft|Fishtrap Config file growthcraft/fishtrap.conf has changed, be sure for check for updates.
[06:29:15] [Server thread/WARN] [Growthcraft|Grapes]: Growthcraft|Grapes Config file growthcraft/grapes.conf has changed, be sure for check for updates.
[06:29:15] [Server thread/WARN] [Growthcraft|Hops]: Growthcraft|Hops Config file growthcraft/hops.conf has changed, be sure for check for updates.
[06:29:25] [Server thread/WARN] [Growthcraft|Milk]: Growthcraft|Milk Config file growthcraft/milk.conf has changed, be sure for check for updates.
[06:29:25] [Server thread/WARN] [Growthcraft|Rice]: Growthcraft|Rice Config file growthcraft/rice.conf has changed, be sure for check for updates.
[06:29:46] [Server thread/INFO] [inpure|core]: Constructing submodule info.inpureprojects.core.Preloader.ModulePreloader
[06:29:46] [Server thread/INFO] [inpure|core]: Constructing submodule info.inpureprojects.core.Scripting.ScriptExtractor
[06:29:46] [Server thread/INFO] [inpure|core]: Processing preinit event for submodule info.inpureprojects.core.Preloader.ModulePreloader
[06:29:46] [Server thread/INFO] [inpure|core]: Processing preinit event for submodule info.inpureprojects.core.Scripting.ScriptExtractor
[06:30:15] [Server thread/INFO] [LogisticsPipes]: Loaded ForestryProxy
[06:30:15] [Server thread/INFO] [LogisticsPipes]: Loaded IC2Proxy
[06:30:15] [Server thread/INFO] [LogisticsPipes]: Loaded CCProxy
[06:30:15] [Server thread/INFO] [LogisticsPipes]: Loaded ThaumCraftProxy
[06:30:15] [Server thread/INFO] [LogisticsPipes]: Loaded ThermalExpansionProxy
[06:30:16] [Server thread/INFO] [LogisticsPipes]: Loaded BetterStorage DummyProxy
[06:30:16] [Server thread/INFO] [LogisticsPipes]: Loaded NEIProxy
[06:30:16] [Server thread/INFO] [LogisticsPipes]: Loaded FactorizationProxy
[06:30:16] [Server thread/INFO] [LogisticsPipes]: Loaded EnderIOProxy
[06:30:16] [Server thread/INFO] [LogisticsPipes]: Loaded IronChestProxy
[06:30:16] [Server thread/INFO] [LogisticsPipes]: Loaded EnderStorageProxy
[06:30:16] [Server thread/INFO] [LogisticsPipes]: Loaded OpenComputersProxy
[06:30:16] [Server thread/INFO] [LogisticsPipes]: Loaded ToolWrenchProxy
[06:30:16] [Server thread/INFO] [LogisticsPipes]: Loaded ExtraCellsProxy
[06:30:16] [Server thread/INFO] [LogisticsPipes]: Loaded CoFHPowerProxy
[06:30:16] [Server thread/INFO] [LogisticsPipes]: Loaded TDProxy
[06:30:16] [Server thread/INFO] [LogisticsPipes]: Loaded BinnieProxy
[06:30:39] [Server thread/INFO] [LogisticsPipes]: Loaded CCLProxy

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Nebnitan** [comment]
[fml-server-latest.log](https://github.com/xJon/The-1.7.10-Pack/files/2304217/fml-server-latest.log)

**Comment by Nebnitan** [comment]
[fml-server-latest.log](https://github.com/xJon/The-1.7.10-Pack/files/2304222/fml-server-latest.log)

**Comment by Nebnitan** [comment]
https://paste.ubuntu.com/p/2Dpm78Xsm3/

**Comment by xJon** [comment]
Try to remove the Flan's Mod from your server and see if it starts.

**Comment by Nebnitan** [comment]
ok so i removed the flans mod jar from the mods folder and it still wont start

https://paste.ubuntu.com/p/SXjQNsms5f/

**Comment by xJon** [comment]
This is just a log of a server loading, not crashing?

**Comment by Nebnitan** [comment]
ok so just to be sure i tried starting it several more times
https://paste.ubuntu.com/p/P5ZZqPG3Vk/
this is what i get

**Comment by xJon** [comment]
Can you explain what happens? Does the game just close upon start?

**Comment by Nebnitan** [comment]
After that last log pops up in the console nothing happens. The server never even comes online. I can’t connect to it and nfoservers tells me it’s offline still.

**Comment by Nebnitan** [comment]
If there’s a problem with the server host I’d be open to switching server providers if you have any recommendations.

**Comment by xJon** [comment]
You might want to contact them, as I'm not sure what the problem is on the modpack's end.

**Comment by Nebnitan** [comment]
Yeah I mean I’m just giving up on this server host because I’m pretty sure it’s on their end anyway. Regardless thanks for the assistance it is much appreciated

**Comment by xJon** [comment]
:)
