### ISSUE TITLE
The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.

### ISSUE THREAD

**Issue by takedafreed** [xJon/The-1.7.10-Pack#1623]
https://pastebin.com/DQbUdxAq

**Comment by xJon** [comment]
1. If you're crashing due to a problematic block or entity, you can try setting these two settings to true in `the-1710-pack\configs\forge.cfg` **after you've backed up your save**:
```
    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=true
```
2. If this doesn't solve the issue you can try to remove the problematic's block/entity's mod and therefor delete all of its content from your save, which might help solve the problem.
3. If this does not work still you can try to manually use NBTExplorer as seen in [this tutorial](https://www.youtube.com/watch?v=fWUUsdp3pJ8).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.

**Comment by ThatDomio** [comment]
Just confirming I had the same error on my modded server and this fixed it. Should I leaves these two values to true afterwards as it says that it can cause catastrophic damage?

**Comment by xJon** [comment]
1.7.10 was worked on so long ago, I'd say don't take the chance :)

**Comment by damionbbbb** [comment]
i was editing my battle towers config for my server on 1.12.2 and I wanted better loot in there but it keeps crashing even tho the config is fine

**Comment by damionbbbb** [comment]
# Configuration file

battletowerchestitems {
    S:"Floor 1"=stick-0-75-5-6;wheat_seeds-0-75-3-5;planks-0-75-5-6;reeds-0-75-3-5;stone_pickaxe-0-50-1-1;stone_axe-0-50-1-1;torch-0-45-3-3;stone_button-0-50-2-2;moarmors:tinpickaxe-0-50-1-2;moarmors:tinaxe-0-50-1-2;spartanshields:shield_tower_tin-0-40-1-2;spartanshields:shield_basic_tin-0-40-1-2;spartanshields:shield_basic_copper-0-60-1-2;moarmors:copperpickaxe-0-60-1-2;moarmors:copperaxe-0-60-1-2;asr:stone_giant_sword-0-50-1-2;hooked:hook-0-30-1-2;string-0-50-3-6;fishing_rod-0-25-1-2;carrot-0-50-8-12;travelersbackpack:travelers_backpack-0-10-1-2;extrabows:stone_bow-0-40-1-2;ic2:ingot-0-50-1-32;ic2:ingot-0-50-1-32;ic2:ingot-0-50-1-32;ic2:ingot-0-50-1-32
    S:"Floor 2"=stick-0-45-5-25;wheat_seeds-0-25-3-5;planks-0-35-5-64;reeds-0-15-3-5;torch-0-45-3-32;moarmors:tinpickaxe-0-20-1-2;moarmors:tinaxe-0-20-1-2;spartanshields:shield_tower_tin-0-30-1-2;spartanshields:shield_basic_tin-0-30-1-2;hooked:hook-0-30-1-2;fishing_rod-0-15-1-2;carrot-0-50-8-12;travelersbackpack:travelers_backpack-0-20-1-2;extrabows:stone_bow-0-40-1-2;ic2:ingot-0-30-1-32;ic2:ingot-0-30-1-32;bowl-0-25-2-4;coal-0-90-4-16;string-0-80-5-10;wool-0-55-2-2;iron_helmet-0-15-1-2;iron_chestplate--0-10-1-2;iron_leggings-0-10-1-2;iron_boots-0-15-1-2;spartanshields:shield_tower_iron-0-10-1-2;spartanshields:shield_basic_iron-0-10-1-2;
    S:"Floor 3"=stick-0-45-5-25;torch-0-45-3-32;hooked:hook-0-30-1-2;fishing_rod-0-15-1-2;carrot-0-50-8-12;travelersbackpack:travelers_backpack-0-20-1-2;extrabows:stone_bow-0-30-1-2;coal-0-90-4-16;string-0-80-5-10;wool-0-55-2-2;iron_ingot-0-20-1-32;asr:iron_giant_sword-0-20-1-2;iron_helmet-0-30-1-2;iron_chestplate-0-20-1-2;iron_leggings-0-20-1-2;iron_boots-0-30-1-2;spartanshields:shield_tower_iron-0-20-1-2;spartanshields:shield_basic_iron-0-20-1-2;glass-0-75-3-3;feather-0-75-4-4;bread-0-75-2-2;apple-0-75-2-2;extrabows:iron_bow-0-25-1-2;extrabows:double_upgrade-0-10-1-1;extrabows:triple_upgrade-0-05-1-1;extrabows:lightning_upgrade-0-05-1-1;extrabows:fire_upgrade-0-05-1-1;extrabows:ender_upgrade-0-05-1-1;extrabows:freeze_upgrade-0-15-1-1;extrabows:explosive_upgrade-0-05-1-1;extrabows:healing_from_damage_upgrade-0-10-1-1;extrabows:arrow_cost_upgrade-0-25-1-1;extrabows:water_upgrade-0-15-1-1;extrabows:push_upgrade-0-10-1-1;extrabows:flying_upgrade-0-05-1-1;extrabows:meteor_upgrade;extrabows:electric_upgrade-0-05-1-1;extrabows:bridge;upgrade-0-25-1-1;rubber-0-45-1-32;
    S:"Floor 4"=brown_mushroom-0-75-2-2;red_mushroom-0-75-2-2;sapling-0-20-3-3;wheat-0-35-4-4;stick-0-45-5-25;torch-0-45-3-32;hooked:hook-0-30-1-2;fishing_rod-0-15-1-2;carrot-0-50-8-12;travelersbackpack:travelers_backpack-0-20-1-2;extrabows:stone_bow-0-50-1-2;coal-0-90-4-16;string-0-80-5-10;wool-0-55-2-2;iron_ingot-0-40-1-32;asr:iron_giant_sword-0-40-1-2;iron_helmet-0-40-1-2;iron_chestplate--0-30-1-2;iron_leggings-0-30-1-2;iron_boots-0-40-1-2;spartanshields:shield_tower_iron-0-40-1-2;spartanshields:shield_basic_iron-0-40-1-2;glass-0-75-3-3;feather-0-75-4-4;bread-0-75-2-2;apple-0-75-2-2;extrabows:iron_bow-0-30-1-2;extrabows:double_arrow_upgrade-0-20-1-1;extrabows:triple_arrow_upgrade-0-10-1-1;extrabows:lightning_upgrade-0-05-1-1;extrabows:fire_upgrade-0-05-1-1;extrabows:ender_upgrade-0-05-1-1;extrabows:freeze_upgrade-0-15-1-1;extrabows:explosive_upgrade-0-05-1-1;extrabows:healing_from_damage_upgrade-0-10-1-1;extrabows:arrow_cost_upgrade-0-25-1-1;extrabows:water_upgrade-0-15-1-1;extrabows:push_upgrade-0-10-1-1;extrabows:flying_upgrade-0-05-1-1;extrabows:meteor_upgrade;extrabows:electric_upgrade-0-05-1-1;extrabows:bridge;upgrade-0-25-1-1;rubber-0-45-1-32;
    S:"Floor 5"=brown_mushroom-0-55-2-2;red_mushroom-0-55-2-2;sapling-0-10-3-3;wheat-0-15-4-4;sign-0-50-1-2;pumpkin_seeds-0-60-2-2;melon_seeds-0-60-3-3;stick-0-45-5-25;torch-0-45-3-32;hooked:hook-0-30-1-2;fishing_rod-0-15-1-2;carrot-0-50-8-12;travelersbackpack:travelers_backpack-0-25-1-2;extrabows:stone_bow-0-50-1-2;coal-0-90-4-16;string-0-80-5-10;wool-0-55-2-2;iron_ingot-0-50-1-32;asr:iron_giant_sword-0-50-1-2;iron_helmet-0-50-1-2;iron_chestplate--0-40-1-2;iron_leggings-0-50-1-2;iron_boots-0-50-1-2;spartanshields:shield_tower_iron-0-50-1-2;spartanshields:shield_basic_iron-0-50-1-2;glass-0-75-3-3;feather-0-75-4-4;bread-0-75-2-2;apple-0-75-2-2;extrabows:iron_bow-0-40-1-2;extrabows:double_arrow_upgrade-0-20-1-1;extrabows:triple_arrow_upgrade-0-10-1-1;extrabows:lightning_upgrade-0-05-1-1;extrabows:fire_upgrade-0-05-1-1;extrabows:ender_upgrade-0-05-1-1;extrabows:freeze_upgrade-0-15-1-1;extrabows:explosive_upgrade-0-05-1-1;extrabows:healing_from_damage_upgrade-0-10-1-1;extrabows:arrow_cost_upgrade-0-25-1-1;extrabows:water_upgrade-0-15-1-1;extrabows:push_upgrade-0-10-1-1;extrabows:flying_upgrade-0-05-1-1;extrabows:meteor_upgrade;extrabows:electric_upgrade-0-05-1-1;extrabows:bridge;upgrade-0-25-1-1;rubber-0-45-1-32;
    S:"Floor 6"=pumpkin_seeds-0-60-2-2;melon_seeds-0-60-3-3;gunpowder-0-75-3-3;leather-0-75-4-4;fish-0-75-3-3;dye-0-60-1-2fishing_rod-0-15-1-2;carrot-0-50-8-12;travelersbackpack:travelers_backpack-0-30-1-2;extrabows:stone_bow-0-30-1-2;coal-0-20-4-16;string-0-40-5-10;wool-0-25-2-2;iron_ingot-0-10-1-32;asr-1.12.2-1.0:iron_giant_sword-0-20-1-2;iron_helmet-0-20-1-2;iron_chestplate--0-10-1-2;iron_leggings-0-20-1-2;iron_boots-0-10-1-2;extrabows:iron_bow-0-35-1-2;extrabows:double_upgrade-0-20-1-1;extrabows:triple_upgrade-0-10-1-1;extrabows:lightning_upgrade-0-05-1-1;extrabows:fire_upgrade-0-05-1-1;extrabows:ender_upgrade-0-05-1-1;extrabows:freeze_upgrade-0-15-1-1;extrabows:explosive_upgrade-0-05-1-1;extrabows:healing_from_damage_upgrade-0-10-1-1;extrabows:arrow_cost_upgrade-0-25-1-1;extrabows:water_upgrade-0-15-1-1;extrabows:push_upgrade-0-10-1-1;extrabows:flying_upgrade-0-05-1-1;extrabows:meteor_upgrade;extrabows:electric_upgrade-0-05-1-1;extrabows:bridge;upgrade-0-25-1-1;rubber-0-45-1-32;
    S:"Floor 7"=gunpowder-0-45-3-3;leather-0-45-4-4;fish-0-15-3-3;dye-0-05-1-2;chainmail_helmet-0-20-1-1;chainmail_chestplate-0-10-1-1;chainmail_leggings-0-10-1-1;chainmail_boots-0-20-1-1;hooked:hook-0-25-1-2;travelersbackpack:travelers_backpack-0-30-1-2;extrabows:iron_bow-0-30-1-2;extrabows:double_upgrade-0-20-1-1;extrabows:triple_upgrade-0-10-1-1;extrabows:lightning_upgrade-0-05-1-1;extrabows-:fire_upgrade-0-05-1-1;extrabows:ender_upgrade-0-05-1-1;extrabows:freeze_upgrade-0-15-1-1;extrabows:explosive_upgrade-0-05-1-1;extrabows:healing_from_damage_upgrade-0-10-1-1;extrabows:arrow_cost_upgrade-0-25-1-1;extrabows:water_upgrade-0-15-1-1;extrabows:push_upgrade-0-10-1-1;extrabows:flying_upgrade-0-05-1-1;extrabows:meteor_upgrade;extrabows:electric_upgrade-0-05-1-1;extrabows:bridge_upgrade-0-25-1-1;rubber-0-45-1-32;ChestGenHook:chests/simple_dungeon:3
    S:"Floor 8"=chainmail_helmet-0-40-1-1;chainmail_chestplate-0-40-1-1;chainmail_leggings-0-40-1-1;chainmail_boots-0-40-1-1;travelersbackpack:travelers_backpack-0-30-1-2;extrabows:iron_bow-0-35-1-2;extrabows:double_upgrade-0-20-1-1;extrabows:triple_upgrade-0-10-1-1;extrabows:lightning_upgrade-0-05-1-1;extrabows:fire_upgrade-0-05-1-1;extrabows:ender_upgrade-0-05-1-1;extrabows:freeze_upgrade-0-15-1-1;extrabows:explosive_upgrade-0-05-1-1;extrabows:healing_from_damage_upgrade-0-10-1-1;extrabows:arrow_cost_upgrade-0-25-1-1;extrabows:water_upgrade-0-15-1-1;extrabows:push_upgrade-0-10-1-1;extrabows:flying_upgrade-0-05-1-1;extrabows:meteor_upgrade;extrabows:electric_upgrade-0-05-1-1;extrabows:bridge;upgrade-0-25-1-1;rubber-0-25-1-32;ChestGenHook:chests/simple_dungeon:3
    S:"Floor 9"=travelersbackpack:travelers_backpack-0-30-1-2;extrabows:emerald_bow-0-40-1-2;moarmors:emeraldarmorhelmet-0-30-1-2;moarmors:emeraldarmorbody-0-15-1-2;moarmors:emeraldarmorlegs-0-15-1-2;moarmors:emeraldarmorboots-0-30-1-2;extrabows:iron_bow-0-40-1-2;extrabows:double_upgrade-0-30-1-1;extrabows:triple_upgrade-0-15-1-1;extrabows:lightning_upgrade-0-10-1-1;extrabows:fire_upgrade-0-10-1-1;extrabows:ender_upgrade-0-10-1-1;extrabows:freeze_upgrade-0-20-1-1;extrabows:explosive_upgrade-0-10-1-1;extrabows:healing_from_damage_upgrade-0-15-1-1;extrabows:arrow_cost_upgrade-0-30-1-1;extrabows:water_upgrade-0-20-1-1;extrabows:push_upgrade-0-15-1-1;extrabows:flying_upgrade-0-10-1-1;extrabows:meteor_upgrade-0-10-1-1;extrabows:electric_upgrade-0-10-1-1;extrabows:bridge;upgrade-0-35-1-1;rubber-0-35-1-32;ender_pearl-0-30-2-2;diamond-0-70-2-2;redstone-0-75-5-5;gold_ingot-0-50-8-8;ChestGenHook:chests/simple_dungeon:5
    S:"Item Generations per Floor"=15
    S:"Top Floor"=ender_pearl-0-50-2-2;diamond-0-70-2-5;redstone-0-75-5-20;gold_ingot-0-90-8-32;;travelersbackpack:travelers_backpack-0-40-1-2;extrabows:emerald_bow-0-30-1-2;moarmors:emeraldarmorhelmet-0-50-1-2;moarmors:emeraldarmorbody-0-40-1-2;moarmors:emeraldarmorlegs-0-50-1-2;moarmors:emeraldarmorboots-0-50-1-2;extrabows:double_upgrade-0-40-1-1;extrabows:triple_upgrade-0-20-1-1;extrabows:lightning_upgrade-0-10-1-1;extrabows:fire_upgrade-0-10-1-1;extrabows:ender_upgrade-0-10-1-1;extrabows:freeze_upgrade-0-25-1-1;extrabows:explosive_upgrade-0-10-1-1;extrabows:healing_from_damage_upgrade-0-20-1-1;extrabows:arrow_cost_upgrade-0-45-1-1;extrabows:water_upgrade-0-30-1-1;extrabows-:push_upgrade-0-10-1-1;extrabows:flying_upgrade-0-10-1-1;extrabows:meteor_upgrade-0-10-1-1;extrabows:electric_upgrade-0-10-1-1;extrabows:bridge_upgrade-0-45-1-1;rubber-0-45-1-32;ChestGenHook:chests/simple_dungeon:7
}


biomespawnallowed {
    B:extreme_hills=true
    B:river=true
    B:roofed_forest=true
}


chunkproviderallowed {
    B:ChunkProviderServer=true
}


mainoptions {
    I:"Minimum Distance between 2 BattleTowers"=196
    I:"Minimum Distance of Battletowers from Spawn"=96
    I:"Tower Destroying Enabled"=1
    I:chanceTowerIsUnderGround=15
    B:noGolemExplosions=false

    # Destroy all Mob Spawners in Tower Area upon Tower Fall?
    B:towerFallDestroysMobSpawners=false
}

**Comment by damionbbbb** [comment]
[17:38:32] [Server thread/INFO] [FML]: Itemstack injection complete
[17:38:32] [Server thread/INFO] [treecapitator]: Prioritizing User and IMC mod configs...
[17:38:32] [Server thread/INFO] [treecapitator]: Registering items and trees...
[17:38:32] [Server thread/INFO] [treecapitator]: Skipping Ore Dictionary processing.
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.Item@27afbf14
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemSeeds@1570cad0
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemMultiTexture@451816fd
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemBlockSpecial@1bb96449
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemPickaxe@1930a804
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemAxe@bd4ee01
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemBlock@4586a8aa
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemBlock@5cc3e49b
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.mcreator.moarmors.item.ItemTinPickaxe$1@529a53b1
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.mcreator.moarmors.item.ItemTinAxe$1@1f7e120f
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook com.oblivioussp.spartanshields.item.ItemShieldExtraMaterial@442fb52d
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook com.oblivioussp.spartanshields.item.ItemShieldExtraMaterial@6967a09d
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook com.oblivioussp.spartanshields.item.ItemShieldExtraMaterial@1b2c31f3
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.mcreator.moarmors.item.ItemCopperPickaxe$1@147e5f
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.mcreator.moarmors.item.ItemCopperAxe$1@13f3e3f8
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook com.mangregory.asgardshieldreloaded.items.tools.ToolSword@7315b69
[17:38:32] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook thecodewarrior.hooked.common.items.ItemHook@5713ede8
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemBlockSpecial@5fb07347
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemFishingRod@6f0c45f4
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemSeedFood@1d3d76b4
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook com.tiviacz.travelersbackpack.items.ItemTravelersBackpack@33a2b2d2
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook me.marnic.extrabows.common.items.bows.ItemStoneBow@5cdc1d31
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook ic2.core.item.ItemMulti@44182083
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook ic2.core.item.ItemMulti@44182083
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook ic2.core.item.ItemMulti@44182083
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook ic2.core.item.ItemMulti@44182083
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.Item@27afbf14
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemSeeds@1570cad0
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemMultiTexture@451816fd
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemBlockSpecial@1bb96449
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemBlock@4586a8aa
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.mcreator.moarmors.item.ItemTinPickaxe$1@529a53b1
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.mcreator.moarmors.item.ItemTinAxe$1@1f7e120f
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook com.oblivioussp.spartanshields.item.ItemShieldExtraMaterial@442fb52d
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook com.oblivioussp.spartanshields.item.ItemShieldExtraMaterial@6967a09d
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook thecodewarrior.hooked.common.items.ItemHook@5713ede8
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemFishingRod@6f0c45f4
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemSeedFood@1d3d76b4
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook com.tiviacz.travelersbackpack.items.ItemTravelersBackpack@33a2b2d2
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook me.marnic.extrabows.common.items.bows.ItemStoneBow@5cdc1d31
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook ic2.core.item.ItemMulti@44182083
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook ic2.core.item.ItemMulti@44182083
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.Item@4cfcac13
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemCoal@7bb4ed71
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemBlockSpecial@5fb07347
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemCloth@6ef037e4
[17:38:33] [Server thread/INFO] [STDOUT]: [atomicstryker.battletowers.common.TowerStageItemManager:<init>:72]: Battletowers parsed Item/Block/ChestGenHook net.minecraft.item.ItemArmor@71f0806b
[17:38:33] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Battle Towers (battletowers)

Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_201]
        at java.lang.Integer.parseInt(Integer.java:592) ~[?:1.8.0_201]
        at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_201]
        at atomicstryker.battletowers.common.TowerStageItemManager.<init>(TowerStageItemManager.java:58) ~[TowerStageItemManager.class:?]
        at atomicstryker.battletowers.common.AS_BattleTowersCore.modsLoaded(AS_BattleTowersCore.java:184) ~[AS_BattleTowersCore.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[17:38:33] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\noobe\Desktop\server\.\crash-reports\crash-2020-11-12_17.38.33-server.txt
[17:38:33] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[17:38:33] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[17:38:33] [Server thread/INFO] [FML]: The state engine was in incorrect state AVAILABLE and forced into state SERVER_STOPPED. Errors may have been discarded.
[17:38:33] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Stopping server
[17:38:33] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Saving worlds

C:\Users\noobe\Desktop\server>pause

**Comment by damionbbbb** [comment]
[crash-2020-11-12_17.38.33-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/5534042/crash-2020-11-12_17.38.33-server.txt)

**Comment by xJon** [comment]
Hey @damionbbbb, if you want to reset the config you can just delete it.
If you want further support please open a new issue.
