### ISSUE TITLE
Can't Launch Server Java PermSize issue??

### ISSUE THREAD

**Issue by hahabtw** [xJon/The-1.7.10-Pack#1701]
OS is 64
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Press any key to continue . . .

**Comment by xJon** [comment]
You need to make sure you have Java SE installed on your computer and not only JDK.

**Comment by TuckerBowlin** [comment]
There are two issues there, the first one, the PermSize is just saying it's being ignored and not doing anything. The second which is everything after that is the issue that I am having. I'm running through ubuntu and getting the same errors as they are getting. I can run a vanilla minecraft server find, but when I try to run the forge-1.7.10-10.13.4.1614-1.7.10-universal.jar it ends up with that issue. I've checked and made sure I have all the proper Java installs I need, so I don't know what to do from there.

**Comment by xJon** [comment]
@TuckerBowlin You're supposed to use the `LaunchServer. files.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.

**Comment by yeems420** [comment]
I'm also having this issue and I'm really confused on what I'm supposed to do to get it fixed. I've installed atleast three different versions of java now, and nothing seems to be helping.
