### ISSUE TITLE
[FIXED] Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by userxxxx-coder** [xJon/The-1.7.10-Pack#1753]
Hello. I've been getting this issue when just exploring my minecraft server. I dont do anything to make this trigger but I may have a suspicion that its my WiFi. After a couple of hours of researching and other stuff this is what I have done :

- Reinstalled Minecraft and Java **thrice**. 
- Restarted my router and played around with the firewall (my router is AT&T btw if that helps).
- Tried installing Netty, but, every time I do it breaks chrome.
- Hosted the server on another machine.

With all this nothing has worked. My friends can join normally but they encounter this error. It happens every 2 1/2-15 mins.
Here is the little message I get from the server side : 
`[18:50:16] [Netty Server IO #0/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_211]
at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_211]
at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_211]
at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_211]
at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_211]
at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446) ~[UnpooledUnsafeDirectByteBuf.class:?]
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[AbstractByteBuf.class:?]
at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225) ~[NioSocketChannel.class:?]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [AbstractNioByteChannel$NioByteUnsafe.class:?]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [NioEventLoop.class:?]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [NioEventLoop.class:?]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [NioEventLoop.class:?]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [NioEventLoop.class:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[14:30:12] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Gkilla510 lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}`
Gkilla510 left the game.

If it is necessary ill post my fml log and latest log, just ask. Gkilla510 is my minecraft name.
Thanks

**Comment by userxxxx-coder** [comment]
Anyone?

**Comment by userxxxx-coder** [comment]
didnt port forward correctly

**Comment by xJon** [comment]
👍
