### ISSUE TITLE
Chrash when i open Inventory

### ISSUE THREAD

**Issue by JustLoveCats** [xJon/The-1.7.10-Pack#1852]
[crash-2019-09-02_20.41.21-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3566327/crash-2019-09-02_20.41.21-client.txt)

**Comment by xJon** [comment]
Please post your log file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Phucketall** [comment]
I am also having the same problem. 

`[00:55:16] [Netty IO #3/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_221]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_221]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_221]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_221]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_221]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]`

**Comment by xJon** [comment]
Please post your crash logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
